-- Deprecated legacy bootstrap migration.
-- The active website schema lives in 20250622110000_website_schema.sql and later files.
-- Do not add new tables here. Kept only for projects that already applied this file.
